services:
  api:
    build:
      context: api/
      dockerfile: Dockerfile
    container_name: uti-api
    command: uvicorn app:application --host 0.0.0.0 --port 7135 --reload
    ports:
      - "7135:7135"
    volumes:
      - ./api:/app
    environment:
      MODELS_DIR: /app/models
    restart: unless-stopped